server:
  port: 8080
  # 全局上下文前缀, 所有 controller @RequestMapping 都不再写 /api
  # 最终访问路径形如: http://localhost:8080/api/user/login
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: fish-oj
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    encoding:
      charset: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/fish_oj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# Sa-Token 配置
sa-token:
  token-name: token
  timeout: 2592000  # 30天
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

codesandbox:
  type: example